---
title: "Health care access"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
runtime: shiny
resource_files:
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.cpg
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.dbf
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.prj
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbn
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbx
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shp.xml
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(sf)
library(ggrepel)
library(scales)
library(shiny)
library(shinycssloaders)
library(ggiraph)
library(kableExtra)
library(rmapshaper)
library(cowplot)
library(DT)
```

```{r loading jon docs and shapefiles, cache=TRUE, include=FALSE}
theme_bar <- theme_bw() +
  theme(panel.grid.major = element_line(color = "grey70", size = 0.1),
        panel.grid.minor = element_blank(),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold"),
        panel.border = element_blank(),
        legend.background = element_rect(fill = "transparent", color = "transparent"),
        legend.key = element_rect(fill = "transparent"),
        legend.title = element_blank(),
        text = element_text(size = 12),
        plot.caption = element_text(hjust = 0.5, face = "italic"),
        legend.text = element_text(margin = margin(l = 2, r = 5)))

theme_line <- theme_bw() +
  theme(legend.background = element_rect(fill = "transparent", color = "transparent"),
        legend.key = element_rect(fill = "transparent"),
        panel.grid.minor = element_blank(),
        panel.grid.major = element_line(color = "grey70", size = 0.1),
        axis.ticks = element_blank(),
        axis.text = element_text(face = "bold"),
        panel.border = element_blank(),
        text = element_text(size = 12),
        plot.caption = element_text(hjust = 0.5, face = "italic"),
        legend.text = element_text(margin = margin(l = 2, r = 5)))

theme_sf <- theme_bw() +
  theme(axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        panel.background = element_blank(),
        panel.grid.major = element_line(color = "white"),
        panel.border = element_blank(),
        plot.title = element_text(hjust = 0.5),
        legend.title = element_blank(),
        text = element_text(size = 12),
        plot.caption = element_text(hjust = 0.5, face = "italic"),
        legend.text = element_text(margin = margin(l = 2, r = 5)))

counties.regions <- read_csv("Data/Join docs/county_regions.csv") %>%
  mutate(countyfp = formatC(countyfp, width = 3, flag = "0"),
         Name = str_to_title(Name),
         Name = str_replace(Name, "Q", "q"),
         Name = str_replace(Name, "Of The", "of the"),
         Dem_Desc = ifelse(Name == "Minnesota", "Minnesota", Dem_Desc),
         Name = str_replace(Name, "Mcleod", "McLeod"),
         planning.region = str_replace(planning.region, " Minnesota", ""),
         edr = str_replace(edr, "  ", " "))

edr.pr <- counties.regions %>%
  distinct(edr, .keep_all = TRUE) %>%
  select(5,6) %>%
  mutate(edr = str_replace(edr, "  ", " "),
         planning.region = str_replace(planning.region, " Minnesota", ""))

color.ruca <- c("Entirely rural" = "#5CA81F", "Town/rural mix" = "#C7EF99", "Urban/town/rural mix" = "#d8b365", "Entirely urban" = "#a6611a", "Minnesota" = "black")

color.pr <- c("Northwest" = "#810f7c","Northeast" = "#fe9929", "Central" = "#076324", "Seven County Mpls-St Paul" = "#d8b365", "Southwest" = "#1f78b4", "Southeast" = "#d7301f", "Minnesota" = "black")

color.edr <- c("EDR 1 - Northwest" = "#b3cde3", "EDR 2 - Headwaters" = "#8c96c6", "EDR 3 - Arrowhead" = "#fe9929", "EDR 4 - West Central" = "#8856a7", "EDR 5 - North Central" = "#810f7c", "EDR 6E- Southwest Central" = "#e5f5f9", "EDR 6W- Upper Minnesota Valley" = "#bdc9e1", "EDR 7E- East Central" = "#99d8c9", "EDR 7W- Central" = "#2ca25f", "EDR 8 - Southwest" = "#74a9cf", "EDR 9 - South Central" = "#0570b0", "EDR 10 - Southeast" = "#d7301f", "EDR 11 - 7 County Twin Cities" = "#d8b365", "Minnesota" = "black")

color.counties <- scale_color_brewer(palette = "Dark2",
                       guide = guide_legend(ncol = 3))

mn_counties <- st_read("Data/Shapefiles/county shapefiles/MNCounties_MNDOT.shp", quiet = TRUE) %>%
  ms_simplify(keep = .01, keep_shapes = TRUE)
```

```{r master objects, include = FALSE, cache=TRUE}
master.ip.distances.ruca <- read_csv("Data/Access/Master-ip-distances-ruca.csv") %>%
  mutate(Dem_Desc = fct_relevel(Dem_Desc, "Entirely rural", "Town/rural mix", "Urban/town/rural mix", "Entirely urban"))

master.ip.distances.pr <- read_csv("Data/Access/Master-ip-distances-pr.csv") %>%
  mutate(planning.region = fct_relevel(planning.region, "Northwest", "Northeast", "Central", "Seven County Mpls-St Paul", "Southwest", "Southeast"))

master.ip.distances.edr <- read_csv("Data/Access/Master-ip-distances-edr.csv") %>%
  mutate(planning.region = str_replace(planning.region, " Minnesota", ""),
         planning.region = fct_relevel(planning.region, "Northwest", "Northeast", "Central", "Seven County Mpls-St Paul", "Southwest", "Southeast"),
         edr = fct_relevel(edr, "EDR 1 - Northwest", "EDR 2 - Headwaters", "EDR 3 - Arrowhead", "EDR 4 - West Central", "EDR 5 - North Central", "EDR 6E- Southwest Central", "EDR 6W- Upper Minnesota Valley", "EDR 7E- East Central", "EDR 7W- Central", "EDR 8 - Southwest", "EDR 9 - South Central", "EDR 10 - Southeast", "EDR 11 - 7 County Twin Cities", "Minnesota"))

master.op.distances.ruca <- read_csv("Data/Access/Master-op-distances-ruca.csv") %>%
  mutate(Dem_Desc = fct_relevel(Dem_Desc, "Entirely rural", "Town/rural mix", "Urban/town/rural mix", "Entirely urban"))

master.op.distances.pr <- read_csv("Data/Access/Master-op-distances-pr.csv") %>%
  mutate(planning.region = str_replace(planning.region, " Minnesota", ""),
         planning.region = fct_relevel(planning.region, "Northwest", "Northeast", "Central", "Seven County Mpls-St Paul", "Southwest", "Southeast"))

master.op.distances.edr <- read_csv("Data/Access/Master-op-distances-edr.csv") %>%
  mutate(planning.region = str_replace(planning.region, " Minnesota", ""),
         planning.region = fct_relevel(planning.region, "Northwest", "Northeast", "Central", "Seven County Mpls-St Paul", "Southwest", "Southeast"),
         edr = fct_relevel(edr, "EDR 1 - Northwest", "EDR 2 - Headwaters", "EDR 3 - Arrowhead", "EDR 4 - West Central", "EDR 5 - North Central", "EDR 6E- Southwest Central", "EDR 6W- Upper Minnesota Valley", "EDR 7E- East Central", "EDR 7W- Central", "EDR 8 - Southwest", "EDR 9 - South Central", "EDR 10 - Southeast", "EDR 11 - 7 County Twin Cities", "Minnesota"))

```

<br>

# Distances traveled by inpatient care and region {.tabset}

Summary here

<br>

## RUCA

As a hospital becomes more rural, the distance their patients travel for a service becomes significantly longer. 

<br>

```{r charts distance traveled inpatient ruca}
ip.ruca.plot <- ggplot(master.ip.distances.ruca, aes(Year, mean.miles, color = Dem_Desc)) +
  geom_smooth(se = FALSE, size = 2) +
  geom_point_interactive(size = 3, aes(data_id = Year, tooltip = paste(Dem_Desc, "\nYear: ", Year, "\nService: ", service.line, "\nAverage miles traveled: ", comma(mean.miles), "\nMedian miles traveled: ", comma(median.miles), sep = ""))) +
  facet_wrap(~service.line, ncol = 2) +
  labs(x="", y = "", color="", title = "Average miles traveled for inpatient service")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(breaks = seq(1900, 2050, 2)) +
  theme_line+
  scale_color_manual(values= color.ruca,
                     guide = guide_legend(ncol = 3)) +
  theme(legend.position = "bottom")

girafe(ggobj = ip.ruca.plot, width_svg = 8) %>%
  girafe_options(opts_selection(type = "none"),
                 opts_toolbar(saveaspng = FALSE) ,
                 opts_sizing(rescale = FALSE))

```

## Planning Region

Analysis here

<br>

```{r charts distance traveled inpatient pr}
ip.pr.plot <- ggplot(master.ip.distances.pr, aes(Year, mean.miles, color = planning.region)) +
  geom_smooth(se = FALSE, size = 2) +
  geom_point_interactive(size = 3, aes(data_id = Year, tooltip = paste(planning.region, "\nYear: ", Year, "\nService: ", service.line, "\nAverage miles traveled: ", comma(mean.miles), "\nMedian miles traveled: ", comma(median.miles), sep = ""))) +
  facet_wrap(~service.line, ncol = 2) +
  labs(x="", y = "", color="", title = "Average miles traveled for inpatient service")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(breaks = seq(1900, 2050, 2)) +
  theme_line+
  scale_color_manual(values= color.pr,
                     guide = guide_legend(ncol = 3)) +
  theme(legend.position = "bottom")

girafe(ggobj = ip.pr.plot, width_svg = 8) %>%
  girafe_options(opts_selection(type = "none"),
                 opts_toolbar(saveaspng = FALSE) ,
                 opts_sizing(rescale = FALSE))
```

## EDR {.tabset}

Analysis here

<br>

### Cardiology

<br>

```{r charts distance traveled inpatient cargiology edr, fig.height=9}
ip.card.edr.plot <- ggplot(filter(master.ip.distances.edr, service.line == "Cardiology"), aes(Year, mean.miles, color = edr)) +
  geom_smooth(se = FALSE, size = 2) +
  geom_point_interactive(size = 3, aes(data_id = Year, tooltip = paste(planning.region, "\nYear: ", Year, "\nService: ", service.line, "\nAverage miles traveled: ", comma(mean.miles), "\nMedian miles traveled: ", comma(median.miles), sep = ""))) +
  facet_wrap(~planning.region, ncol = 2) +
  labs(x="", y = "", color="", title = "Average miles traveled for inpatient service - cardiology")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(breaks = seq(1900, 2050, 2)) +
  theme_line+
  scale_color_manual(values= color.edr,
                     guide = guide_legend(ncol = 3)) +
  theme(legend.position = "bottom")

girafe(ggobj = ip.card.edr.plot, height_svg = 8) %>%
  girafe_options(opts_selection(type = "none"),
                 opts_toolbar(saveaspng = FALSE) ,
                 opts_sizing(rescale = FALSE))
```

### Neurology

<br>

```{r charts distance traveled inpatient neurology edr, fig.height=9}
ip.neur.edr.plot <- ggplot(filter(master.ip.distances.edr, service.line == "Neurology"), aes(Year, mean.miles, color = edr)) +
  geom_smooth(se = FALSE, size = 2) +
  geom_point_interactive(size = 3, aes(data_id = Year, tooltip = paste(planning.region, "\nYear: ", Year, "\nService: ", service.line, "\nAverage miles traveled: ", comma(mean.miles), "\nMedian miles traveled: ", comma(median.miles), sep = ""))) +
  facet_wrap(~planning.region, ncol = 2) +
  labs(x="", y = "", color="", title = "Average miles traveled for inpatient service - neurology")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(breaks = seq(1900, 2050, 2)) +
  theme_line+
  scale_color_manual(values= color.edr,
                     guide = guide_legend(ncol = 3)) +
  theme(legend.position = "bottom")

girafe(ggobj = ip.neur.edr.plot, height_svg = 8) %>%
  girafe_options(opts_selection(type = "none"),
                 opts_toolbar(saveaspng = FALSE) ,
                 opts_sizing(rescale = FALSE))
```

### Obstetrics

<br>

```{r charts distance traveled inpatient obstetrics edr, fig.height=9}

ip.obs.edr.plot <- ggplot(filter(master.ip.distances.edr, service.line == "Obstetrics"), aes(Year, mean.miles, color = edr)) +
  geom_smooth(se = FALSE, size = 2) +
  geom_point_interactive(size = 3, aes(data_id = Year, tooltip = paste(planning.region, "\nYear: ", Year, "\nService: ", service.line, "\nAverage miles traveled: ", comma(mean.miles), "\nMedian miles traveled: ", comma(median.miles), sep = ""))) +
  facet_wrap(~planning.region, ncol = 2) +
  labs(x="", y = "", color="", title = "Average miles traveled for inpatient service - obstetrics")+
  scale_y_continuous(labels=scales::comma)+
  scale_x_continuous(breaks = seq(1900, 2050, 2)) +
  theme_line+
  scale_color_manual(values= color.edr,
                     guide = guide_legend(ncol = 3)) +
  theme(legend.position = "bottom")

girafe(ggobj = ip.obs.edr.plot, height_svg = 8) %>%
  girafe_options(opts_selection(type = "none"),
                 opts_toolbar(saveaspng = FALSE) ,
                 opts_sizing(rescale = FALSE))
```
