---
title: "Summary and data overview"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 4
runtime: shiny
resource_files:
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.cpg
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.dbf
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.prj
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbn
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.sbx
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shp.xml
- Data/Shapefiles/County shapefiles/MNCounties_MNDOT.shx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(tidyverse)
library(sf)
library(ggrepel)
library(scales)
library(shiny)
library(shinycssloaders)
library(ggiraph)
library(kableExtra)
library(rmapshaper)
library(cowplot)
library(DT)
```

<br>

# Summary

## Number of hospitals

There were 140 hospitals reporting financial data in 2018, down from 145 in 2014. The hospital losses occurred in Southwest (1), Seven County Metro (2), Central (2), and Southeast (1). 

When looking at the percentage of hospitals that are designated as Critical Access Hospitals (CAH), the highest percentages are located outside of the seven county metro. The highest percentage is located in Southwest Minnesota where over 90% of their hospitals have CAH designation. Central, Northwest and Northeast all have a majority of their hospitals designated as CAHs.

## Net income or losses

There is definitely a pattern in the percentage of hospitals that are experiencing a net loss and the rural-ness of a hospital's location. Since 2014, our entirely rural hospitals have had a higher percentage of their hospitals experiencing a net loss. The percentages decrease as counties become more urban.

In 2018, 50% of the hospitals in Entirely rural counties were experiencing a net loss, while 44.4%, 22.9%, and 13.6% of hospitals were in town/rural mix, urban/town/rural mix, and entirely urban counties, respectively.

When broken down by planning regions, Southwest has the highest percentage of hospitals experiencing a net loss with 48%, followed by Northeast (47%) and Northwest (25%).

## Margins

Again, rural-ness of a hospital's location tends to have major impacts on a hospital's margins. In 2018, our entirely rural counties had an average margin of 0.1%, while our town/rural mix, urban/town/rural mix and entirely urban counties averaged margins of 1.8%, 3.1%, and 6.2% respectively.

A margin of 4% is considered "healthy" by most economists since it allows a hospital to meet with obligations while providing a bit more to reinvest into the hospital. When analyzing the percentage of hospitals that had a margins below 4%, again rural-ness matters. In 2018, 69% of hospitals had margins below 4%, while our town/rural mix, urban/town/rural mix and entirely urban hospitals had 56%, 45% and 32%, respectively.

## Payer mix

The percentage of charges to a patient that is publicly insured is much higher for hospitals in entirely rural areas. In 2018, hospitals in entirely rural areas averaged 70% of their charges to patients in public programs, while town/rural mix, urban/town/rural mix, and entirely urban counties averaged 66.2%, 64.7% and 60.9% of their charges, respectively.

Since 2014, the percentages have increased significantly across all areas. Across all types of counties, the percentages have increased between 5 and 7 percentage points since 2014.

## Admissions

Admissions by public payer patients makes up a significantly higher percentage in rural hospitals compared to metro. In 2018, 85% of admissions were by patients in a public program, while town/rural mix, urban/town/rural mix and entirely urban hospitals averaged 77%, 76% and 62% respectively.

<br>

# About the data

This analysis uses the Hospital Annual Report (HAR) data provided by every hospital in the state. Hospitals are required to provide an immense amount of information regarding their financial state, including breakdowns of revenue and expenses, such as the amount of uncompensated care, salaries for various staff, revenue by each department/type of service provided within the hospital, and the amount of revenue from Medicare, Medicaid, etc...

The data I have here goes back to 2014. The data is broken down by each hospital id and the value for each question of the report, which is designated by a code. For example, the code 0200 represents the income/loss from operations line in the HAR report.

<br>
